#!/bin/bash

#Asset declaration scraper -- scrapes and processes http://declaration.ge
#Copyright 2012 Transparency International Georgia http://transparency.ge
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

# edit this to suit your configuration
HOST="http://localhost:5984"
DB="declarations"
BASENAME="/usr/bin/basename"
CUT="/usr/bin/cut"
CURL="/usr/bin/curl"

COMMAND="$1"
case $COMMAND in
    "del")
        $CURL -X DELETE $HOST/$DB;;
    "upview")
        # $2 == design document
        docname=`$BASENAME $2 | $CUT -f1 -d.`
        $CURL -X PUT $HOST/$DB/_design/$docname --data @$2;;
    "downview")
        # $2 == design document
        $CURL -X GET $HOST/$DB/_design/$2 > $2.json;;
    "repviews")
        # $2 == target db
        $CURL -X POST -H "Content-Type: application/json" -d "{\"source\": \"$DB\", \"target\": \"$2\", \"doc_ids\": [\"_design/forexport\", \"_design/basic\"]}" "$HOST/_replicate";;
    "rep")
        # $2 == target db
        #$CURL -X DELETE $HOST/$2;
        $CURL -X PUT $HOST/$2;
        $CURL -X POST -H "Content-Type: application/json" -d "{\"source\": \"$DB\", \"target\": \"$2\"}" "$HOST/_replicate";;
esac
