#!/bin/bash
#
# Download reports on income declarations from declaration.ge
#
# It runs in an infinite loop, counting IDs up. It is stopped if there had
# been 1000 consecutive failed IDs to download.
#
# It takes one optional parameter:
# $1 - directory to write PDF files to
#
#############################################################################

SRC="http://declaration.ge/csb/report/report.seam?id="
ENG="&lang=2"
STOP=1000
CURL=/usr/bin/curl
EN_FOLDER="en"
KA_FOLDER="ka"

#############################################################################

# Setup session
# No longer needed thanks to my awesome blog post.
#curl -c cookies.txt http://declaration.ge
#curl -c cookies.txt -b cookies.txt http://declaration.ge/csb/main.seam
#curl -c cookies.txt -b cookies.txt http://declaration.ge/csb/public.seam
#curl -c cookies.txt -b cookies.txt -d "" http://declaration.ge/csb/public.seam

if [ -n "$1" ]; then
    echo "Entering $1"
    cd $1
    echo "Making language directories"
    mkdir $EN_FOLDER && mkdir $KA_FOLDER
fi

c=0
miss=0
count=0
while [ $miss -le $STOP ]
do
    echo "Trying report ID $c"
	$CURL --progress-bar --output $KA_FOLDER/report-$c.pdf "$SRC$c"
	if [ ! -e $KA_FOLDER/report-$c.pdf ]
	then
		miss=`expr $miss + 1`
	else
		miss=0
        count=`expr $count + 1`
        # Once we know the Georgian version exists, try to download Eng.
        $CURL --progress-bar --output $EN_FOLDER/report-$c.pdf "$SRC$c$ENG"
	fi
	c=`expr $c + 1`
	#echo $c, $miss
done

echo "Downloaded $count declarations (not files)."
if [ -n "$1" ]; then
    echo "Leaving $1"
    cd -
fi
